### ISSUE TITLE
`neonctl auth` fails with `ERROR: Socket connection timeout`

### ISSUE THREAD

**Issue by prasadlakmal** [neondatabase/neonctl#215]
## Steps to reproduce
Followed the steps as mentioned in the quick start guide, on a fresh installation.
* `npm install -g neonctl`
* `neonctl auth`

## Expected result
A browser window should spin up to get the authentication done.

## Actual result
Seeing the error in the console. 
`ERROR: Socket connection timeout`

## Environment
**OS**: Pop!_OS 22.04 LTS x86_64
**Node**: 20.0.0

## Logs, links
Ater cloning the repo, these were the debug logs I was able to collect by running it locally with `DEBUG=true node dist auth`

```
➜  neonctl git:(main) ✗ DEBUG=true node dist auth
DEBUG: Failed to read credentials file Error: ENOENT: no such file or directory, open '/home/prasadl/.config/neonctl/credentials.json'
    at Object.openSync (node:fs:590:3)
    at readFileSync (node:fs:458:35)
    at analyticsMiddleware (file:///home/prasadl/Projects/neonctl/dist/analytics.js:19:29)
    at file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/middleware.js:82:28
    at Array.reduce (<anonymous>)
    at applyMiddleware (file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/middleware.js:67:24)
    at CommandInstance.applyMiddlewareAndGetResult (file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/command.js:242:34)
    at CommandInstance.runCommand (file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/command.js:128:20)
    at [runYargsParserAndExecuteCommands] (file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/yargs-factory.js:1386:105)
    at YargsInstance.parse (file:///home/prasadl/Projects/neonctl/node_modules/yargs/build/lib/yargs-factory.js:707:63) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/prasadl/.config/neonctl/credentials.json'
}
DEBUG: Flushing CLI started event with userId: 
DEBUG: Flushed CLI started event with userId: 
DEBUG: Discovering oauth server
DEBUG: Sent CLI error event: UNKNOWN_ERROR
ERROR: Socket connection timeout
DEBUG: Stack: Error [ERR_SOCKET_CONNECTION_TIMEOUT]: Socket connection timeout
    at new NodeError (node:internal/errors:399:5)
    at internalConnectMultiple (node:net:1098:20)
    at Timeout.internalConnectMultipleTimeout (node:net:1637:3)
    at listOnTimeout (node:internal/timers:575:11)
    at process.processTimers (node:internal/timers:514:7)
```

**Comment by Shridhad** [comment]
Probably, the same root case as https://github.com/neondatabase/neonctl/issues/216. However, it is no longer reproducible. 

@prasadlakmal Can you please upgrade `neonctl` version to 1.29.5 and verify it's still an issue for you?

closing as duplicate.
